l=(1,3,2,4,5)
print(l[1:3])
b=(3,6)
print("concating tuple l and b")
print(l+b)
print("index of 3 is",l.index(3))
print("count of is",l.count(3))
# l.sort()
print("after sorting",l)
print("sum of all elements=",sum(l))
# l.clear()
print()